#!/bin/sh
# commit changes to git repository
if [ -z "${1}" ]; then
  printf "Enter a short description:  "
  read descr;
  if [[ -z ${descr} ]]; then echo No input found; exit; fi
else
  descr=$1;
fi
git commit -a --message="$descr"